// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"main/pkg/api"
	"main/pkg/api/handler"
	"main/pkg/config"
	"main/pkg/db"
	"main/pkg/repository"
	"main/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}

	inventoryRepository:=repository.NewInventoryRepository(gormDB)
	inventoryUseCase:=usecase.NewInventoryUseCase(inventoryRepository)
	inventoryHandler:=handler.NewInventoryHandler(inventoryUseCase)

	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)



	orderRepository:=repository.NewOrderRepository(gormDB)
	orderUseCase:=usecase.NewOrderUseCase(orderRepository,userUseCase)
	orderHandler:=handler.NewOrderHandler(orderUseCase)

	adminRepository:=repository.NewAdminRepository(gormDB)
	adminUseCase:=usecase.NewAdminUseCase(adminRepository)
	adminHandler:=handler.NewAdminHandler(adminUseCase)

	serverHTTP := http.NewServerHTTP(inventoryHandler,userHandler,adminHandler,orderHandler)

	return serverHTTP, nil
}